import { z } from "zod";
import { routingSchema } from "../model-routing.ts";
import type { Scope } from "../types.ts";
import {
  preparationContext,
  preparationSelection,
  strategySchema,
} from "../preparation-contracts.ts";
export type Effect =
  | "READ_ONLY"
  | "STATE_WRITE"
  | "FUTURE_CONSEQUENCE"
  | "EXTERNAL_PROVIDER_EFFECT"
  | "AUTHORITY_CHANGE"
  | "FINANCIAL_EFFECT";
const id = z
  .string()
  .min(1)
  .max(100)
  .regex(/^[a-zA-Z0-9_-]+$/);
const key = z.string().min(8).max(128);
const empty = z.strictObject({});
const campaign = z.strictObject({ campaign: id });
const text = z.record(id, z.string().min(1).max(12500));
const when = z.string().max(80);
export interface Operation {
  name: string;
  description: string;
  scope: Scope;
  tier: "free" | "advanced";
  effects: Effect[];
  schema: z.ZodType;
  example: unknown;
  inspection: string;
  retry: string;
}
function op(
  name: string,
  description: string,
  scope: Scope,
  effects: Effect[],
  schema: z.ZodType,
  example: unknown,
  inspection: string,
  tier: "free" | "advanced" = "free",
): Operation {
  return {
    name,
    description,
    scope,
    tier,
    effects,
    schema,
    example,
    inspection,
    retry: effects.every((x) => x === "READ_ONLY")
      ? "Safe to repeat."
      : "Reuse the same idempotencyKey and exact inputs. Inspect status after disconnection; never create a fresh key to bypass an uncertain result.",
  };
}
export const catalog: Operation[] = [
  op(
    "autonomy_request",
    "Ask the standing producer to fill an actual stock deficit using owner-selected sources and context. Reuses an existing durable request. Agent model spending still requires owner consent.",
    "campaign:write",
    ["STATE_WRITE", "FINANCIAL_EFFECT", "FUTURE_CONSEQUENCE"],
    z.strictObject({ project: id, idempotencyKey: key }),
    { project: "product", idempotencyKey: "autonomy-request-001" },
    "autonomy_list",
    "advanced",
  ),
  op(
    "autonomy_list",
    "Inspect standing project authority, stock request and editorial holds.",
    "read",
    ["READ_ONLY"],
    empty,
    {},
    "autonomy_list",
  ),
  op(
    "autonomy_configure",
    "Owner setup consent for recurring evidence-grounded preparation and paced publishing. Clean checks proceed without per-copy approval; existing manual deliveries remain unchanged.",
    "admin",
    [
      "STATE_WRITE",
      "AUTHORITY_CHANGE",
      "FUTURE_CONSEQUENCE",
      "FINANCIAL_EFFECT",
    ],
    z.strictObject({
      project: id,
      selection: preparationSelection,
      context: preparationContext,
      enabled: z.boolean(),
      intervalMinutes: z.number().int().min(15).max(10080),
      stockFloor: z.number().int().min(1).max(3),
      maxDailyDeliveries: z.number().int().min(1).max(100),
      idempotencyKey: key,
    }),
    {
      project: "product",
      selection: {
        repository: "owner/product",
        releaseTag: "v1.0",
        documentationPaths: ["README.md"],
        allowPrivate: false,
        allowUnreleased: false,
      },
      context: {
        audience: "Builders delegating release communications",
        objective: "Explain useful documented capabilities to potential users",
        brandVoice: "Specific British English",
        productContext: "A source-grounded publishing product",
        exclusions: "No unsupported outcomes",
        callToAction: "Read the documentation",
      },
      enabled: true,
      intervalMinutes: 240,
      stockFloor: 2,
      maxDailyDeliveries: 3,
      idempotencyKey: "autonomy-setup-001",
    },
    "autonomy_list",
    "advanced",
  ),
  op(
    "autonomy_pause",
    "Owner revocation of standing publishing and generation authority. Captured deliveries stop before further provider writes.",
    "admin",
    ["STATE_WRITE", "AUTHORITY_CHANGE"],
    z.strictObject({ project: id, idempotencyKey: key }),
    { project: "product", idempotencyKey: "autonomy-pause-001" },
    "autonomy_list",
  ),

  op(
    "model_status",
    "Inspect this workspace’s own model connection and bounded usage. No key is returned.",
    "read",
    ["READ_ONLY"],
    empty,
    {},
    "model_status",
  ),
  op(
    "model_connect",
    "Owner-only: connect workspace-owned OpenAI or Cloudflare credentials and explicit routing/spend policy. Cloudflare validation reads metadata only; no inference, top-up or shared gateway mutation occurs.",
    "admin",
    ["AUTHORITY_CHANGE"],
    z.strictObject({
      apiKey: z.string().min(16).max(512).optional(),
      inspectionToken: z.string().min(16).max(512).optional(),
      routing: routingSchema.optional(),
      maxJobsPerDay: z.number().int().min(1).max(8),
      allowAgents: z.boolean(),
      inputUsdPerMillion: z.number().min(0).max(1000).nullable(),
      outputUsdPerMillion: z.number().min(0).max(1000).nullable(),
      maxDailyUsd: z.number().min(0.01).max(100).nullable(),
      idempotencyKey: key,
    }),
    {
      apiKey: "OWNER_SUPPLIED_API_KEY",
      maxJobsPerDay: 2,
      allowAgents: false,
      inputUsdPerMillion: null,
      outputUsdPerMillion: null,
      maxDailyUsd: null,
      idempotencyKey: "model-connect-001",
    },
    "model_status",
  ),
  op(
    "model_disconnect",
    "Owner-only: disconnect workspace model access and fence queued/in-flight generation.",
    "admin",
    ["AUTHORITY_CHANGE"],
    z.strictObject({ idempotencyKey: key }),
    { idempotencyKey: "model-disconnect-001" },
    "model_status",
  ),
  op(
    "preparations_list",
    "Inspect private preparation strategy, evidence, drafts, review states and model usage; never provider/model credentials.",
    "read",
    ["READ_ONLY"],
    empty,
    {},
    "preparations_list",
  ),
  op(
    "preparation_export",
    "Export a private preparation and the exact digest required for reviewed removal. No credential or publication effect.",
    "read",
    ["READ_ONLY"],
    z.strictObject({ id }),
    { id: "RETURNED_PREPARATION_ID" },
    "preparations_list",
  ),
  op(
    "preparation_archive",
    "Owner-only: remove an exported terminal preparation from the active library. Retains immutable campaigns, receipts, spending and existing operation history.",
    "admin",
    ["STATE_WRITE"],
    z.strictObject({
      id,
      revision: z.number().int().positive(),
      reviewDigest: z.string().regex(/^[a-f0-9]{64}$/),
      idempotencyKey: key,
    }),
    {
      id: "RETURNED_PREPARATION_ID",
      revision: 1,
      reviewDigest: "a".repeat(64),
      idempotencyKey: "preparation-archive-001",
    },
    "preparations_list",
  ),
  op(
    "preparation_project_put",
    "Create cloud editorial project-to-account context for AI preparation in either executor mode. This never creates local runtime projects or schedules.",
    "campaign:write",
    ["STATE_WRITE"],
    z.strictObject({
      id,
      name: z.string().min(1).max(100),
      accounts: z.array(id).min(1).max(3),
      idempotencyKey: key,
    }),
    {
      id: "product",
      name: "Product preparation",
      accounts: ["product_x"],
      idempotencyKey: "preparation-project-001",
    },
    "workspace_status",
  ),
  op(
    "preparation_create",
    "Queue original AI release interpretation, campaign strategy, drafting and editorial checks using the workspace’s own bounded model account. Never publishes or schedules.",
    "campaign:write",
    ["STATE_WRITE", "FINANCIAL_EFFECT"],
    z.strictObject({
      project: id,
      selection: preparationSelection,
      context: preparationContext,
      idempotencyKey: key,
    }),
    {
      project: "launch",
      selection: {
        repository: "owner/repository",
        releaseTag: "v1.0",
        documentationPaths: ["README.md"],
        allowPrivate: false,
        allowUnreleased: false,
      },
      context: {
        audience: "Operators maintaining release communications",
        objective: "Explain the practical value of this release",
        brandVoice: "Clear British English",
        productContext: "A product for reviewed release communications",
        exclusions: "No unsupported availability claims",
        callToAction: "Read the release notes",
      },
      idempotencyKey: "prepare-release-001",
    },
    "preparations_list",
  ),
  op(
    "preparation_edit",
    "Edit or remove selected draft variants and strategy. Edits invalidate checking/approval and never change an immutable handed-off campaign.",
    "campaign:write",
    ["STATE_WRITE"],
    z.strictObject({
      id,
      revision: z.number().int().positive(),
      text,
      strategy: strategySchema.optional(),
      idempotencyKey: key,
    }),
    {
      id: "RETURNED_PREPARATION_ID",
      revision: 1,
      text: { product_x: "Owner-edited text" },
      idempotencyKey: "preparation-edit-001",
    },
    "preparations_list",
  ),
  op(
    "preparation_regenerate",
    "Explicitly spend bounded model allowance to regenerate strategy, all/one draft, or check edited drafts. Uncertain calls are never retried automatically.",
    "campaign:write",
    ["STATE_WRITE", "FINANCIAL_EFFECT"],
    z.strictObject({
      id,
      revision: z.number().int().positive(),
      stage: z.enum(["interpret", "draft", "check"]),
      alias: id.optional(),
      context: preparationContext.optional(),
      idempotencyKey: key,
    }),
    {
      id: "RETURNED_PREPARATION_ID",
      revision: 1,
      stage: "draft",
      alias: "product_x",
      idempotencyKey: "preparation-regenerate-001",
    },
    "preparations_list",
  ),
  op(
    "preparation_reject",
    "Reject private preparation and fence any in-flight output; no publication or schedule is created.",
    "campaign:write",
    ["STATE_WRITE"],
    z.strictObject({
      id,
      revision: z.number().int().positive(),
      idempotencyKey: key,
    }),
    {
      id: "RETURNED_PREPARATION_ID",
      revision: 1,
      idempotencyKey: "preparation-reject-001",
    },
    "preparations_list",
  ),
  op(
    "preparation_approve",
    "Signed-in owner reviews exact revision/digest, current account bindings and evidence, then freezes variants into an immutable campaign. Scheduling remains a separate explicit action.",
    "admin",
    ["STATE_WRITE"],
    z.strictObject({
      id,
      revision: z.number().int().positive(),
      digest: z.string().regex(/^[a-f0-9]{64}$/),
      idempotencyKey: key,
    }),
    {
      id: "RETURNED_PREPARATION_ID",
      revision: 1,
      digest: "a".repeat(64),
      idempotencyKey: "preparation-approve-001",
    },
    "preparations_list",
  ),
  op(
    "workspace_status",
    "Inspect workspace, entitlement, limits and publication pause.",
    "read",
    ["READ_ONLY"],
    empty,
    {},
    "workspace_status",
  ),
  op(
    "publishing_capabilities",
    "Inspect implemented publication formats, live provider-app configuration, connected stable identities, owner-approval behavior and the one-shot acceptance URL.",
    "read",
    ["READ_ONLY"],
    empty,
    {},
    "publishing_capabilities",
  ),
  op(
    "accounts_list",
    "Read verified account identities and binding versions. Credentials are never returned.",
    "read",
    ["READ_ONLY"],
    empty,
    {},
    "accounts_list",
  ),
  op(
    "account_disconnect",
    "Revoke a connection and block its future unclaimed deliveries.",
    "connections",
    ["AUTHORITY_CHANGE", "FUTURE_CONSEQUENCE"],
    z.strictObject({ alias: id, idempotencyKey: key }),
    { alias: "product_x", idempotencyKey: "disconnect-001" },
    "accounts_list",
  ),
  op(
    "project_put",
    "Create or replace explicit project-to-account routing. Existing deliveries retain their captured bindings.",
    "campaign:write",
    ["STATE_WRITE"],
    z.strictObject({
      id,
      name: z.string().min(1).max(100),
      accounts: z.array(id).min(1).max(10),
      idempotencyKey: key,
    }),
    {
      id: "product",
      name: "Product",
      accounts: ["product_x"],
      idempotencyKey: "project-001",
    },
    "projects_list",
  ),
  op(
    "projects_list",
    "List project routing.",
    "read",
    ["READ_ONLY"],
    empty,
    {},
    "projects_list",
  ),
  op(
    "campaign_create",
    "Store immutable, exact text per account alias. No copy is generated or truncated.",
    "campaign:write",
    ["STATE_WRITE"],
    z.strictObject({ project: id, text, idempotencyKey: key }),
    {
      project: "product",
      text: { product_x: "A reviewed product update." },
      idempotencyKey: "campaign-001",
    },
    "campaign_get",
  ),
  op(
    "campaign_get",
    "Inspect exact content and its immutable digest.",
    "read",
    ["READ_ONLY"],
    campaign,
    { campaign: "campaign-id" },
    "campaign_get",
  ),
  op(
    "campaign_validate",
    "Dry-run routing and provider text validation without publication.",
    "read",
    ["READ_ONLY"],
    campaign,
    { campaign: "campaign-id" },
    "campaign_get",
  ),
  op(
    "publish_now",
    "Reserve each campaign delivery once and dispatch through durable alarms. Returns receipt IDs immediately; inspect receipts for actual outcome.",
    "publish",
    ["STATE_WRITE", "EXTERNAL_PROVIDER_EFFECT"],
    z.strictObject({ campaign: id, idempotencyKey: key }),
    { campaign: "campaign-id", idempotencyKey: "publish-001" },
    "receipts_list",
  ),
  op(
    "schedule_create",
    "Schedule exact immutable campaign content at an explicit time with UTC offset.",
    "schedule",
    ["STATE_WRITE", "FUTURE_CONSEQUENCE"],
    z.strictObject({
      campaign: id,
      at: when,
      timezone: z.string().default("UTC"),
      idempotencyKey: key,
    }),
    {
      campaign: "campaign-id",
      at: "2026-10-01T12:00:00Z",
      timezone: "UTC",
      idempotencyKey: "schedule-001",
    },
    "receipts_list",
  ),
  op(
    "schedule_cancel",
    "Cancel one unclaimed delivery. Reports already executing if dispatch won the race.",
    "schedule",
    ["STATE_WRITE", "FUTURE_CONSEQUENCE"],
    z.strictObject({ delivery: id, idempotencyKey: key }),
    { delivery: "delivery-id", idempotencyKey: "cancel-001" },
    "receipt_get",
  ),
  op(
    "delivery_approve",
    "Owner-review an agent-created delivery and release its immutable account, identity, text and schedule reservation. The original agent authority is still rechecked at dispatch.",
    "publish",
    ["AUTHORITY_CHANGE", "FUTURE_CONSEQUENCE"],
    z.strictObject({ delivery: id, idempotencyKey: key }),
    { delivery: "delivery-id", idempotencyKey: "approve-001" },
    "receipt_get",
  ),
  op(
    "delivery_reject",
    "Owner-reject an agent-created delivery before any provider write.",
    "publish",
    ["AUTHORITY_CHANGE", "FUTURE_CONSEQUENCE"],
    z.strictObject({ delivery: id, idempotencyKey: key }),
    { delivery: "delivery-id", idempotencyKey: "reject-001" },
    "receipt_get",
  ),
  op(
    "schedule_replace",
    "Atomically cancel an unclaimed delivery and reserve a reviewed replacement campaign for the same account.",
    "schedule",
    ["STATE_WRITE", "FUTURE_CONSEQUENCE"],
    z.strictObject({
      delivery: id,
      campaign: id,
      at: when,
      timezone: z.string().default("UTC"),
      idempotencyKey: key,
    }),
    {
      delivery: "delivery-id",
      campaign: "replacement-id",
      at: "2026-10-01T13:00:00Z",
      timezone: "UTC",
      idempotencyKey: "replace-001",
    },
    "receipt_get",
  ),
  op(
    "receipt_get",
    "Inspect provider evidence, status and reason for one delivery.",
    "read",
    ["READ_ONLY"],
    z.strictObject({ delivery: id }),
    { delivery: "delivery-id" },
    "receipt_get",
  ),
  op(
    "receipt_recheck",
    "Verify the recorded post ID, stable author and exact text without publishing again. At most eight recovery reads, at least sixty seconds apart. Already verified receipts return unchanged.",
    "read",
    ["STATE_WRITE"],
    z.strictObject({ delivery: id, idempotencyKey: key }),
    { delivery: "delivery-id", idempotencyKey: "readback-001" },
    "receipt_get",
  ),
  op(
    "receipts_list",
    "Read delivery history. An unverified ID and an ambiguous effect are distinct from verified publication.",
    "read",
    ["READ_ONLY"],
    z.strictObject({
      limit: z.number().int().min(1).max(200).default(50),
      before: z.number().optional(),
    }),
    { limit: 50 },
    "receipts_list",
  ),
  op(
    "workspace_export",
    "Export project, campaign and receipt records; excludes credentials and payment tokens.",
    "read",
    ["READ_ONLY"],
    empty,
    {},
    "workspace_export",
  ),
  op(
    "metrics_capture",
    "Capture available provider metrics on demand. Unsupported or inaccessible metrics are returned as unavailable, never fabricated zeros.",
    "read",
    ["STATE_WRITE"],
    z.strictObject({ delivery: id, idempotencyKey: key }),
    { delivery: "delivery-id", idempotencyKey: "metrics-001" },
    "receipt_get",
  ),
  op(
    "publishing_pause",
    "Pause or resume all new workspace publication claims. In-flight effects may still finish.",
    "publish",
    ["AUTHORITY_CHANGE", "FUTURE_CONSEQUENCE"],
    z.strictObject({ paused: z.boolean(), idempotencyKey: key }),
    { paused: true, idempotencyKey: "pause-001" },
    "workspace_status",
  ),
  op(
    "automation_configure",
    "Store an explicitly reviewed repository profile and exact approved templates. Configuration starts paused. Repository input never grants authority.",
    "automation",
    ["STATE_WRITE"],
    z.strictObject({
      id,
      project: id,
      repository: z.string().regex(/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/),
      branch: z.string().min(1).max(200),
      path: z.string().min(1).max(300),
      templates: text,
      family: id,
      intervalMinutes: z.number().int().min(15).max(10080),
      minSpacingMinutes: z.number().int().min(15).max(10080),
      idempotencyKey: key,
    }),
    {
      id: "release",
      project: "product",
      repository: "owner/product",
      branch: "main",
      path: "README.md",
      templates: {
        product_x:
          "Development update: reviewed source changed in https://github.com/owner/product.",
      },
      family: "development",
      intervalMinutes: 60,
      minSpacingMinutes: 60,
      idempotencyKey: "profile-001",
    },
    "automation_inspect",
    "advanced",
  ),
  op(
    "automation_inspect",
    "Inspect profiles, source snapshots, decisions and pending automated deliveries. Inspection remains free after subscription expiry.",
    "read",
    ["READ_ONLY"],
    empty,
    {},
    "automation_inspect",
  ),
  op(
    "automation_preview",
    "Check the selected source and show the next permitted allocation without storing inventory or schedules.",
    "automation",
    ["READ_ONLY"],
    z.strictObject({ id }),
    { id: "release" },
    "automation_inspect",
    "advanced",
  ),
  op(
    "automation_enable",
    "Enable bounded continuing authority for this reviewed profile. Payment alone does not grant posting authority.",
    "automation",
    ["AUTHORITY_CHANGE", "FUTURE_CONSEQUENCE"],
    z.strictObject({ id, idempotencyKey: key }),
    { id: "release", idempotencyKey: "enable-001" },
    "automation_inspect",
    "advanced",
  ),
  op(
    "automation_pause",
    "Pause a profile and cancel its unclaimed automated deliveries. Always available, including after expiry.",
    "automation",
    ["AUTHORITY_CHANGE", "FUTURE_CONSEQUENCE"],
    z.strictObject({ id, idempotencyKey: key }),
    { id: "release", idempotencyKey: "autopause-001" },
    "automation_inspect",
  ),
  op(
    "billing_status",
    "Inspect confirmed paid-through access and payment method availability.",
    "read",
    ["READ_ONLY"],
    empty,
    {},
    "billing_status",
  ),
  op(
    "billing_quote",
    "Create an exact configured GBP workspace purchase quote: recurring subscription or non-renewing calendar month.",
    "billing",
    ["STATE_WRITE"],
    z.strictObject({
      mode: z.enum(["subscription", "pass"]),
      idempotencyKey: key,
    }),
    { mode: "subscription", idempotencyKey: "quote-001" },
    "billing_status",
  ),
  op(
    "billing_checkout",
    "Create or retrieve Stripe-hosted subscription checkout for an unexpired quote. Checkout creation does not grant access.",
    "billing",
    ["FINANCIAL_EFFECT"],
    z.strictObject({ quote: id, idempotencyKey: key }),
    { quote: "quote-id", idempotencyKey: "checkout-001" },
    "billing_status",
  ),
  op(
    "billing_portal",
    "Open the Stripe customer portal to inspect invoices or manage renewal.",
    "billing",
    ["STATE_WRITE"],
    z.strictObject({ idempotencyKey: key }),
    { idempotencyKey: "portal-001" },
    "billing_status",
  ),
];
catalog.push(
  op(
    "runtime_inspect",
    "Queue bounded inspection of the active local executor. Read runtime_command_get for the result; this is not hosted workspace state.",
    "read",
    ["READ_ONLY"],
    z.strictObject({
      view: z.enum(["status", "projects", "campaigns", "schedules"]),
      idempotencyKey: key,
    }),
    { view: "schedules", idempotencyKey: "local-inspect-001" },
    "runtime_command_get",
  ),
  op(
    "runtime_schedule_create",
    "Queue an exact local campaign/provider schedule on the reviewed local executor. Original agent authority is rechecked before provider effects.",
    "schedule",
    ["STATE_WRITE", "FUTURE_CONSEQUENCE"],
    z.strictObject({
      campaign: z.string().regex(/^[A-Z][A-Z0-9-]{2,63}$/),
      provider: z.enum(["x", "threads", "linkedin"]),
      at: when,
      timezone: z.string().max(80).default("UTC"),
      idempotencyKey: key,
    }),
    {
      campaign: "PRODUCT-001",
      provider: "threads",
      at: "2026-10-01T12:00:00Z",
      idempotencyKey: "local-schedule-001",
    },
    "runtime_command_get",
  ),
  op(
    "runtime_schedule_cancel",
    "Queue cancellation of one unclaimed local schedule; never changes executor or owner authority.",
    "schedule",
    ["STATE_WRITE"],
    z.strictObject({
      scheduleId: z.string().regex(/^sch_[a-f0-9]{32}$/),
      idempotencyKey: key,
    }),
    { scheduleId: "sch_" + "a".repeat(32), idempotencyKey: "local-cancel-001" },
    "runtime_command_get",
  ),
  op(
    "runtime_command_get",
    "Read a durable command receipt for this actor. Claimed work is never automatically redispatched; provider receipts remain separate.",
    "read",
    ["READ_ONLY"],
    z.strictObject({ commandId: z.uuid() }),
    { commandId: "11111111-1111-4111-8111-111111111111" },
    "runtime_command_get",
  ),
);
export const byName = new Map(catalog.map((o) => [o.name, o]));
export function describe(o: Operation) {
  const { schema, ...rest } = o;
  return {
    ...rest,
    inputSchema: z.toJSONSchema(schema),
    annotations: {
      readOnlyHint: o.effects.every((x) => x === "READ_ONLY"),
      destructiveHint:
        o.effects.includes("FUTURE_CONSEQUENCE") ||
        o.effects.includes("EXTERNAL_PROVIDER_EFFECT"),
      idempotentHint: true,
      openWorldHint:
        o.effects.includes("EXTERNAL_PROVIDER_EFFECT") ||
        o.effects.includes("FINANCIAL_EFFECT"),
    },
  };
}
export const plans = {
  currency: "gbp",
  free: {
    amount: 0,
    features: [
      "publishing",
      "explicit_scheduling",
      "routing",
      "receipts",
      "on_demand_metrics",
      "all_agent_transports",
    ],
  },
  advanced: {
    amount: null,
    priceStatus: "not_configured",
    interval: "month",
    features: [
      "source_monitoring",
      "replenishment",
      "rolling_allocation",
      "spacing_controls",
      "scheduled_metrics",
    ],
  },
  providerCharges:
    "Provider API charges, where applicable, are separate. X uses the configured PostSteward OAuth application.",
  overages: "No automatic overage charges.",
};
